In [2]:
import numpy as np

In [3]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])

In [4]:
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [5]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [6]:
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [7]:
data.shape


(2, 3)

In [8]:
my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

In [9]:
%timeit my_arr2 = my_arr * 2

238 μs ± 5.51 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [10]:
%timeit my_list2 = [x*2 for x in my_list]

16.7 ms ± 584 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [11]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [13]:
arr2d[:2][1:]

array([[4, 5, 6]])

In [14]:
arr2d[1][2]

np.int64(6)

In [15]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])

In [4]:
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [5]:
arr.T

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])

In [10]:
np.arange(15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [11]:
np.random.standard_normal(size=(4,4))

array([[ 0.58239775, -0.65383075, -0.77707338,  0.57618755],
       [ 0.29376956, -1.10125322,  2.17665217, -0.67101679],
       [ 0.9135367 , -1.24416591, -0.50894129, -0.35599   ],
       [-0.9900378 , -1.15880642,  0.98298879,  0.05735282]])

In [3]:
points = np.arange(-5, 5, 0.01)

In [4]:
xs, ys = np.meshgrid(points, points)

In [5]:
points

array([-5.0000000e+00, -4.9900000e+00, -4.9800000e+00, -4.9700000e+00,
       -4.9600000e+00, -4.9500000e+00, -4.9400000e+00, -4.9300000e+00,
       -4.9200000e+00, -4.9100000e+00, -4.9000000e+00, -4.8900000e+00,
       -4.8800000e+00, -4.8700000e+00, -4.8600000e+00, -4.8500000e+00,
       -4.8400000e+00, -4.8300000e+00, -4.8200000e+00, -4.8100000e+00,
       -4.8000000e+00, -4.7900000e+00, -4.7800000e+00, -4.7700000e+00,
       -4.7600000e+00, -4.7500000e+00, -4.7400000e+00, -4.7300000e+00,
       -4.7200000e+00, -4.7100000e+00, -4.7000000e+00, -4.6900000e+00,
       -4.6800000e+00, -4.6700000e+00, -4.6600000e+00, -4.6500000e+00,
       -4.6400000e+00, -4.6300000e+00, -4.6200000e+00, -4.6100000e+00,
       -4.6000000e+00, -4.5900000e+00, -4.5800000e+00, -4.5700000e+00,
       -4.5600000e+00, -4.5500000e+00, -4.5400000e+00, -4.5300000e+00,
       -4.5200000e+00, -4.5100000e+00, -4.5000000e+00, -4.4900000e+00,
       -4.4800000e+00, -4.4700000e+00, -4.4600000e+00, -4.4500000e+00,
      

In [6]:
arr = rng.standard_normal((4, 4))

NameError: name 'rng' is not defined

In [7]:
rng = np.random.default_rng(seed=12345)

In [8]:
draws = rng.integers(0, 2, size=1000)

In [10]:
import pandas as pd

In [11]:
pd.Series([4, 7, -5, 3])

0    4
1    7
2   -5
3    3
dtype: int64

In [12]:
obj = pd.Series([4, 7, -5, 3])

In [13]:
obj.array

<NumpyExtensionArray>
[4, 7, -5, 3]
Length: 4, dtype: int64

In [14]:
obj = pd.Series([4, 7, -5, 3])

In [15]:
obj


0    4
1    7
2   -5
3    3
dtype: int64